title: Nacional Móveis
description: >
  Encante-se

baseurl: "" 
url: "https://nacionalmoveis.com.br/" 

favicon: "/img/favicon.png"
img: "/img/"

collections:
  acabamentos:
    output: true
  produtos:
    output: true
    permalink: /produtos/:path/
  posts:
    output: true


permalink: pretty

# Build settings
markdown: kramdown